### PR TITLE
Robot state

### PR DESCRIPTION
**Pull request by anasarrak**
Changed the whole robot_state to compile with colcon. Transform isn't ported yet, so it displays some errors refering to it.

### CODE REVIEW

**Comment by vmayoral** [comment]
Thanks @anasarrak, I’ll review this tonight. Please move it the next submodule if possible.

**Comment by anasarrak** [comment]
Once finished with trasforms uncomment this https://github.com/AcutronicRobotics/moveit2/blob/6ca09e1d5b8e483de40df4aaa1821d1667f7c81d/moveit_core/robot_state/include/moveit/robot_state/conversions.h#L41

**Comment by vmayoral** [comment]
Beyond the issues with transform, still suffering from the following issue @anasarrak:

```bash
/Users/victor/moveit_research/moveit/moveit_core/robot_state/src/conversions.cpp:535:62: error: cannot pass object of non-trivial type 'const std::__1::__vector_base<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::value_type' (aka 'const std::__1::basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
      ROS_ERROR_NAMED(LOGNAME.c_str(), "Missing variable " , state.getVariableNames()[i]);
                                                             ^
/Users/victor/moveit_research/moveit/moveit_core/logging/include/moveit/logging/logging.h:41:25: note: expanded from macro 'ROS_ERROR_NAMED'
#define ROS_ERROR_NAMED RCUTILS_LOG_ERROR

```

**Comment by vmayoral** [comment]
Also, we should try to port the unit tests. Pending items then:
- [ ] Port unit tests
- [ ] Fix type error https://github.com/AcutronicRobotics/moveit2/pull/6#issuecomment-464850136
- [ ] Finalize transform (note: transform has a similar issue than the one described in https://github.com/AcutronicRobotics/moveit2/pull/6#issuecomment-464850136 thereby both things seem connected)

**Comment by anasarrak** [comment]
Closing this, already ported here https://github.com/AcutronicRobotics/moveit2/tree/master/moveit_core/robot_state

**Pull request closed without merging**
